-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 23:26:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tipper` DEFAULT CHARACTER SET utf8 ;
USE `tipper` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipper`.`account` (
  `id` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `point` INT NOT NULL,
  `createTime` TIMESTAMP NOT NULL,
  `used` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipper`.`post` (
  `post` TEXT(5000) NOT NULL,
  `category` TINYTEXT NOT NULL,
  `createTime` TIMESTAMP NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `title` TINYTEXT NOT NULL,
  `like` INT NOT NULL,
  `disLike` INT NOT NULL,
  `view` INT NOT NULL,
  `salesVolume` INT NOT NULL,
  `categoryRank` INT NOT NULL,
  `wholeRank` INT NOT NULL,
  `account_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_post_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipper`.`comment` (
  `comment` TEXT(100) NOT NULL,
  `createTime` TIMESTAMP NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `post_id` VARCHAR(45) NOT NULL,
  `account_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  INDEX `fk_comment_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipper`.`report` (
  `reportId` INT NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `reportTime` TIMESTAMP NOT NULL,
  `post_id` VARCHAR(45) NOT NULL,
  `account_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_post1_idx` (`post_id` ASC),
  INDEX `fk_report_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_report_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
